SECRET_KEY = 'a54bZ45jds459034BzKK023Jz123YTzn7ysd'
DATABASE_NAME = 'bubble'
DATABASE_IP = 'localhost'
DATABASE_PORT = 5432
DATABASE_USER = 'postgres'
DATABASE_PASSWORD = 'root'
UPLOAD_FOLDER = 'C:\\Users\\Gaylord\\PycharmProjects\\bubble\\main\\static\\all_music'
MAIN_URL = 'http://127.0.0.1:5000'
# MAIL_SERVER = 'smtp.yandex.ru'
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
# MAIL_USERNAME = 'opera.operaciy@yandex.ru'
# MAIL_PASSWORD = 'ofalfwomjxzmihkb'
MAIL_USERNAME = 'lineage5553@gmail.com'
MAIL_PASSWORD = 'xoctpuhkapmgvdef'
MAIL_DEFAULT_SENDER = 'opera.operaciy@yandex.ru'
