version: '3.8'

# volumes - это, скажем так, место куда сохраняются наши данные, некая область выделяемая docker
volumes:
  postgresql_data_bubble:
  application_data_bubble:

services:
  postgresql:
    image: postgres:16
    container_name: database_bubble
    restart: always
    command: -p 6543
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: bubble
    volumes:
      - postgresql_data_bubble:/var/lib/postgresql/data
    # expose - это порты открытые для других контейнеров, но не открыты во вне
    expose:
      - "6543:6543"
    # ports - это порты открытые во вне контейнера
    # зачем это делать? - Чтобы можно было бы зайти в базу и посмотреть на данные, в любом случае
    # вы закроете этот порт чтобы он не бил в глобал, но будет доступен например через vpn или из-под машины
    ports:
      - "6543:6543"
  bubble:
    build:
      context: . # тут мы говорим что собираем наш проект относительно текущей директории
    container_name: bubble # мне кажется тут не стоит объяснять
    # command - это команда выполняемая при запуске приложения
    command: sh start.sh
    # environment - переменные среды окружения, мы их используем в качестве настройки
    environment:
      - TZ=Asia/Novosibirsk
      - DATABASE_NAME=bubble
      - DATABASE_IP=postgresql
      - DATABASE_PORT=6543
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - MAIN_URL=http://0.0.0.0:8000
      - API_IMAGE=http://0.0.0.0:8000/api/image/
      - API_MUSIC=http://0.0.0.0:8000/api/music/
      - MAX_FILE_SIZE = 1073741824 # 1 * 1024 * 1024 * 1024
    volumes:
      - application_data_bubble:/bubble/stored_files
    # restart - это говорим что если докер будет перезапущен, то и наше приложение будет перезагружено
    restart: always
    ports:
      - "8000:8000"
    # depends_on - это зависимость, пока не соберётся база данных, мы не будем собирать приложение
    depends_on:
      - postgresql